name: radar-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gdal
  - rasterio
  - cartopy
  - pyproj
  - shapely
  - fiona
  - xarray
  - netCDF4
  - h5py
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pip
  - pip:
      - arm_pyart==2.1.0
      - cmweather==0.3.2
      - open-radar-data==0.5.0
      - rio-cogeo==5.4.2
      - rio-stac==0.8.1
      - rio-tiler==7.8.1
      - rioxarray==0.19.0
      - cogeo-mosaic==8.2.0
      - titiler-application==0.22.4
      - titiler-core==0.22.4
      - titiler-extensions==0.22.4
      - titiler-mosaic==0.22.4
      - fastapi==0.116.1
      - uvicorn==0.35.0
      - starlette==0.47.2
      - httpx==0.28.1
      - websockets==15.0.1
      - PySide6==6.9.1
      - cmweather==0.3.2
      - geojson-pydantic==2.0.0
      - pystac==1.13.0
      - morecantile==6.2.0
      - supermorecado==0.1.2
      - dask==2025.7.0
      - s3fs==2025.7.0
      - fsspec==2025.7.0
      - xradar==0.10.0
      - aiohttp==3.12.15
      - aiobotocore==2.24.1
      - anyio==4.10.0
      - pydantic==2.11.7
      - pydantic-settings==2.10.1
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
